[package]
name = "diesel_postgres_crud"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2", features = ["postgres", "r2d2","chrono"] }
dotenv = "0.15.0"
postgres =  { version = "0.19.0"}